import { CATEGORY_PRESETS, CHANNEL_OPTIONS, QUIZ_QUESTIONS } from '@/data/categoryPresets'
import { COVERAGE_OPTIONS, MATERIAL_OPTIONS, REFINEMENT_QUESTIONS, STRIP_OPTIONS } from '@/data/refinements'
import { BUDGET_BANDS, QUANTITY_BANDS } from '@/data/bands'

/**
 * Every string the question cards put on screen, keyed by a stable id.
 *
 * It is built from the same data the cards render rather than copied, so a new
 * category or band cannot be added without its copy joining the bundle. English
 * is the source language; other languages come back from the model and are
 * cached per language (see LanguageProvider).
 */
export type Dict = Record<string, string>

/** Bumped whenever the set of ids changes, so stale caches are dropped. */
export const BUNDLE_VERSION = 2

const UI_CHROME: Dict = {
  'chrome.exactNumber': 'An exact number',
  'chrome.exactNumberHint': 'e.g. 250',
  'chrome.pcs': 'pcs',
  'chrome.exactAmount': 'An exact amount',
  'chrome.exactAmountHint': 'e.g. 1.20',
  'chrome.perPiece': '/pc',
  'chrome.skipAll': 'Skip all',
  'chrome.next': 'Next',
  'chrome.noPreferenceRest': 'No preference on the rest',
  'chrome.skipRest': 'Skip the rest of the questions',
  'chrome.width': 'Width',
  'chrome.height': 'Height',
  'chrome.depth': 'Depth',
  'chrome.downloadSpec': 'Download specification',
  // The PDF: labels only. Every value in it comes from the keys above.
  'spec.title': 'Packaging specification',
  'spec.subtitle': 'Everything settled in this conversation.',
  'spec.brief': 'The brief',
  'spec.refinements': 'Narrowing',
  'spec.choice': 'Chosen direction',
  'spec.product': 'What is being packed',
  'spec.purpose': 'Packaging purpose',
  'spec.dimensions': 'Product dimensions',
  'spec.quantity': 'Quantity',
  'spec.budget': 'Budget for the run',
  'spec.material': 'Material colour',
  'spec.coverage': 'Print coverage',
  'spec.strip': 'Adhesive strip',
  'spec.look': 'Look',
  'spec.eco': 'Recycled or recyclable required',
  'spec.food': 'Food contact',
  'spec.format': 'Format',
  'spec.size': 'Size',
  'spec.unitPrice': 'Price per piece',
  'spec.total': 'Total',
  'spec.notSet': 'not set',
  'spec.yes': 'Yes',
  'spec.estimated': 'Estimated price — not a binding quote.',
  'spec.footer': 'Generated by Packfinder. Prices are indicative until confirmed by Packhelp.',
}

export function buildBundle(): Dict {
  const dict: Dict = { ...UI_CHROME }

  QUIZ_QUESTIONS.forEach((question, index) => {
    dict[`quiz.${index}`] = question
  })
  REFINEMENT_QUESTIONS.forEach((question, index) => {
    dict[`refine.${index}`] = question
  })

  for (const preset of CATEGORY_PRESETS) {
    dict[`cat.${preset.id}.label`] = preset.label
    dict[`cat.${preset.id}.blurb`] = preset.blurb
  }
  for (const option of CHANNEL_OPTIONS) {
    dict[`channel.${option.id}.label`] = option.label
    dict[`channel.${option.id}.blurb`] = option.blurb
  }
  for (const band of [...QUANTITY_BANDS, ...BUDGET_BANDS]) {
    dict[`band.${band.id}.title`] = band.title
    dict[`band.${band.id}.description`] = band.description
  }
  for (const [group, options] of [
    ['material', MATERIAL_OPTIONS],
    ['coverage', COVERAGE_OPTIONS],
    ['strip', STRIP_OPTIONS],
  ] as const) {
    for (const option of options) {
      dict[`${group}.${option.value}.title`] = option.title
      dict[`${group}.${option.value}.description`] = option.description
    }
  }

  return dict
}
